#### Bayesian networks generated by this script are without interventional data (to investigate effects of interventional data). ####
library(bnlearn)
library(parallel)

path <- "/path/to/dir/"

# Define region of interest
regType <- c(hct116_cpgrich_MU = "hct116_cpgrich_MU", hct116_cpgpoor_MU = "hct116_cpgpoor_MU")

################################################################################
# MAP Bayesian
################################################################################

# Create output directory
if (!dir.exists(paste0(path, "bayesianNetworksDiscretized_MAP"))){
  dir.create(paste0(path, "bayesianNetworksDiscretized_MAP"), recursive = T)}

################################################################################
# Use observational data to learn Bayesian networks
################################################################################

for(i in 1:length(regType)){
  
  # Load observational data (discretized consolidated matrices)
  dat <- readRDS(paste0(path, "summarizedMatrix/All_Consolidated_Epigenomes_Discretized/", regType[[i]], "_discretized.RDS"))
  
  # Replicate 1
  dat_r1 <- dat[["Replicate1"]]
  dat_r1 <- apply(dat_r1, 2, as.character)
  dat_r1 <- data.frame(dat_r1, stringsAsFactors = T)
  
  # Replicate 2
  dat_r2 <- dat[["Replicate2"]]
  dat_r2 <- apply(dat_r2, 2, as.character)
  dat_r2 <- data.frame(dat_r2, stringsAsFactors = T)
  
  # Define blacklist to exclude direction from expression to any other variables
  bl <- data.frame(from = "Expression", to = colnames(dat_r1))
  bl <- bl[-which(bl$to == "Expression"), ]
  
  # Structure learning
  # Start from a set of random graphs
  nodes <- names(dat_r1)
  init <- random.graph(nodes = nodes, method = 'melancon', num = 500, burn.in = 10^5, every = 100)
  
  # Tune each random graphs with data
  netlist_r1 <- lapply(init, function(net){tabu(dat_r1, score = 'bde', start = net, tabu = 50, blacklist = bl)})
  netlist_r2 <- lapply(init, function(net){tabu(dat_r2, score = 'bde', start = net, tabu = 50, blacklist = bl)})
  
  # Take resulting list to compute arc strengths
  strength_r1 <- custom.strength(netlist_r1, nodes = nodes, cpdag = F)
  strength_r2 <- custom.strength(netlist_r2, nodes = nodes, cpdag = F)
  strength <- mean(strength_r1, strength_r2)
  
  # Model averaging
  strength_filt <- strength[strength$strength > 0.85 & strength$direction > 0.5,]
  dag_average <- averaged.network(strength_filt, threshold = 0.85)
  dag_average$learning$blacklist <- bl
  #dag_average$arc_strength <- strength_filt
  dag_average$arc_strength <- strength #More flexible for downstream operations
  
  # Save results of structure learning
  saveRDS(dag_average, paste0(path, "bayesianNetworksDiscretized_MAP/no_int_", regType[[i]], ".RDS"))
}

################################################################################
# Frequentist (bootstrap)
################################################################################

cores_cnt = makeCluster(60)

# Create output directory
if (!dir.exists(paste0(path, "bayesianNetworksDiscretized_bootstrap"))){
  dir.create(paste0(path, "bayesianNetworksDiscretized_bootstrap"), recursive = T)}

################################################################################
# Use observational data to learn Bayesian networks
################################################################################

for(i in 1:length(regType)){
  
  # Load observational data (discretized consolidated matrices)
  dat <- readRDS(paste0(path, "summarizedMatrix/All_Consolidated_Epigenomes_Discretized/", regType[[i]], "_discretized.RDS"))
  
  # Replicate 1
  dat_r1 <- dat[["Replicate1"]]
  dat_r1 <- apply(dat_r1, 2, as.character)
  dat_r1 <- data.frame(dat_r1, stringsAsFactors = T)
  
  # Replicate 2
  dat_r2 <- dat[["Replicate2"]]
  dat_r2 <- apply(dat_r2, 2, as.character)
  dat_r2 <- data.frame(dat_r2, stringsAsFactors = T)
  
  # Define blacklist to exclude direction from expression to any other variables
  bl <- data.frame(from = "Expression", to = colnames(dat_r1))
  bl <- bl[-which(bl$to == "Expression"), ]
  
  # Structure learning
  strength_r1 = boot.strength(dat_r1, algorithm = "tabu",
                              algorithm.args = list(score = "aic", tabu = 20, blacklist = bl),
                              cluster = cores_cnt, R = 1000, cpdag = F, m = round(nrow(dat_r1) * 0.85))
  strength_r2 = boot.strength(dat_r2, algorithm = "tabu",
                              algorithm.args = list(score = "aic", tabu = 20, blacklist = bl),
                              cluster = cores_cnt, R = 1000, cpdag = F, m = round(nrow(dat_r1) * 0.85))
  strength <- mean(strength_r1, strength_r2)
  
  # Model averaging
  strength_filt <- strength[strength$strength > 0.90 & strength$direction > 0.5,]
  dag_average <- averaged.network(strength, threshold = 0.75)
  dag_average$learning$blacklist <- bl
  dag_average$arc_strength <- strength
  
  # Save results of structure learning
  saveRDS(dag_average, paste0(path, "bayesianNetworksDiscretized_bootstrap/no_int_", regType[[i]], ".RDS"))
}
stopCluster(cores_cnt)
